#!/bin/bash
set -euo pipefail

# =========[ Wymagania / sanity ]=========
if [[ $EUID -ne 0 ]]; then
  echo "❌ Uruchom jako root: sudo $0"
  exit 1
fi

command -v ip >/dev/null || { echo "❌ Brak 'ip'"; exit 1; }

# =========[ Helpery ]=========
ask() { # ask "Pytanie" "domyślna_wartość"
  local prompt="$1" default="${2:-}"
  if [[ -n "$default" ]]; then
    read -rp "$prompt [$default]: " ans || true
    echo "${ans:-$default}"
  else
    read -rp "$prompt: " ans || true
    echo "$ans"
  fi
}

confirm() { # confirm "tekst"
  read -rp "$1 [y/N]: " _c || true
  [[ "${_c,,}" == "y" || "${_c,,}" == "yes" ]]
}

netmask_to_prefix() { # "255.255.255.0" -> "24"
  local mask="$1" IFS=.; read -ra o <<< "$mask"
  local bin=""; for n in "${o[@]}"; do bin+=$(printf "%08d" "$(bc <<< "obase=2;$n")"); done
  echo "${bin%%0*}" | wc -c
}

# =========[ MENU GŁÓWNE ]=========
while :; do
  echo
  echo "========== VM04 SETUP =========="
  echo "1) Konfiguracja sieci (LAN + WAN)"
  echo "2) NAT (MASQUERADE / SNAT / DNAT)  + zapis /root/nat.sh"
  echo "3) DNS (bind9) – zadanie nr 3"
  echo "4) Podsumowanie / testy"
  echo "0) Wyjście"
  echo "================================"
  read -rp "Wybór: " CH || true

  case "$CH" in
  1)
    echo "=== [1] Sieć: LAN + WAN ==="
    # ---- LAN ----
    LAN_IF=$(ask "Nazwa interfejsu LAN" "eth0")
    LAN_IP=$(ask "Adres IP LAN (bez maski)" "10.21.137.254")
    LAN_MASK=$(ask "Maska LAN" "255.255.255.0")
    LAN_PREFIX=$(netmask_to_prefix "$LAN_MASK")

    # ---- WAN ----
    WAN_IF=$(ask "Nazwa interfejsu WAN" "eth2")
    WAN_IP=$(ask "Adres IP WAN (bez maski)" "192.168.76.137")
    WAN_MASK=$(ask "Maska WAN" "255.255.255.0")
    WAN_PREFIX=$(netmask_to_prefix "$WAN_MASK")
    WAN_GW=$(ask "Brama (gateway) dla WAN" "192.168.76.1")
    WAN_DNS=$(ask "DNS(y) (spacja) dla WAN" "8.8.8.8 8.8.4.4")

    echo
    echo "👉 Zapisuję /etc/network/interfaces (ifupdown – zgodne z LAB01)"
    cp -a /etc/network/interfaces /etc/network/interfaces.bak.$(date +%s) || true
    cat >/etc/network/interfaces <<EOF
# Generated by vm04_setup.sh
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto ${LAN_IF}
iface ${LAN_IF} inet static
    address ${LAN_IP}
    netmask ${LAN_MASK}

auto ${WAN_IF}
iface ${WAN_IF} inet static
    address ${WAN_IP}
    netmask ${WAN_MASK}
    gateway ${WAN_GW}
    dns-nameservers ${WAN_DNS}
EOF

    echo "🔄 Restart networking..."
    if systemctl is-active --quiet networking 2>/dev/null; then
      systemctl restart networking || true
    else
      service networking restart || true
    fi

    echo "✅ Sieć ustawiona."
    echo "LAN: ${LAN_IF} -> ${LAN_IP}/${LAN_PREFIX}"
    echo "WAN: ${WAN_IF} -> ${WAN_IP}/${WAN_PREFIX}, GW=${WAN_GW}, DNS='${WAN_DNS}'"
    ;;

  2)
    echo "=== [2] NAT ==="
    # Zbierz dane (część może pochodzić z pkt 1 – ale dopytamy, żeby było niezależne)
    LAN_IF=$(ask "Interfejs LAN" "eth0")
    WAN_IF=$(ask "Interfejs WAN" "eth2")
    LAN_SUBNET=$(ask "Podsieć LAN (CIDR)" "10.21.137.0/24")
    WAN_EXT_IP=$(ask "Zewnętrzny IP WAN (dla SNAT --to-source)" "192.168.76.137")

    echo
    echo "Wybierz akcje NAT (możesz kilka):"
    DO_MASK=false; DO_SNAT=false; DO_DNAT=false
    confirm "Włączyć MASQUERADE dla ${LAN_SUBNET} przez ${WAN_IF}?" && DO_MASK=true
    confirm "Dodać SNAT (--to-source ${WAN_EXT_IP}) dla ${LAN_SUBNET}?" && DO_SNAT=true
    confirm "Skonfigurować DNAT (port forwarding)?" && DO_DNAT=true

    # Domyślne mapowania DNAT zgodne z Twoim labo
    if $DO_DNAT; then
      EXT_IP=$(ask "Adres zewnętrzny (na którym nasłuch DNAT)" "${WAN_EXT_IP}")
      VM01_IP=$(ask "IP VM01 (SSH/WWW)" "10.21.137.11")
      VM02_IP=$(ask "IP VM02 (SSH/WWW)" "10.21.137.12")
      DNAT_SSH1_PORT=$(ask "Port zewnętrzny -> VM01:22" "1001")
      DNAT_SSH2_PORT=$(ask "Port zewnętrzny -> VM02:22" "2002")
      DNAT_WEB1_PORT=$(ask "Port zewnętrzny -> VM01:80" "8016")
      DNAT_WEB2_PORT=$(ask "Port zewnętrzny -> VM02:80" "8006")
    fi

    echo "👉 Tworzę /root/nat.sh i stosuję reguły…"
    cat >/root/nat.sh <<EOF
#!/bin/bash
set -euo pipefail
echo 1 > /proc/sys/net/ipv4/ip_forward

# wipe
iptables -F
iptables -t nat -F
iptables -X

# ===== MASQUERADE =====
EOF

    if $DO_MASK; then
      cat >>/root/nat.sh <<EOF
iptables -t nat -A POSTROUTING -s ${LAN_SUBNET} -o ${WAN_IF} -j MASQUERADE
EOF
    fi

    # SNAT alternatywnie do MASQUERADE (statyczny IP)
    if $DO_SNAT; then
      cat >>/root/nat.sh <<EOF
iptables -t nat -A POSTROUTING -s ${LAN_SUBNET} -o ${WAN_IF} -j SNAT --to-source ${WAN_EXT_IP}
EOF
    fi

    # DNAT rules (opcjonalnie)
    if $DO_DNAT; then
      cat >>/root/nat.sh <<EOF

# ===== DNAT (port forwarding) =====
iptables -t nat -A PREROUTING -i ${WAN_IF} -p tcp -d ${EXT_IP} --dport ${DNAT_SSH1_PORT} -j DNAT --to-destination ${VM01_IP}:22
iptables -t nat -A PREROUTING -i ${WAN_IF} -p tcp -d ${EXT_IP} --dport ${DNAT_SSH2_PORT} -j DNAT --to-destination ${VM02_IP}:22

iptables -t nat -A PREROUTING -i ${WAN_IF} -p tcp -d ${EXT_IP} --dport ${DNAT_WEB1_PORT} -j DNAT --to-destination ${VM01_IP}:80
iptables -t nat -A PREROUTING -i ${WAN_IF} -p tcp -d ${EXT_IP} --dport ${DNAT_WEB2_PORT} -j DNAT --to-destination ${VM02_IP}:80
EOF
    fi

    cat >>/root/nat.sh <<'EOF'

# podgląd
iptables -L -v
iptables -t nat -L -v
EOF

    chmod +x /root/nat.sh
    bash /root/nat.sh

    echo "✅ NAT zastosowany. Skrypt: /root/nat.sh"
    echo "💡 Testy: ssh -p <port> <EXT_IP> | curl http://<EXT_IP>:<port>"

    ;;

  3)
    echo "=== [3] DNS (bind9) – zadanie nr 3 ==="
    NR=$(ask "Podaj swój numer (POD)" "137")
    BLOG_IP=$(ask "IP dla ${NR}.blog.pl (i aliasu ${NR}.edu.lab)" "10.21.${NR}.11")
    BIZ_IP=$(ask "IP dla ${NR}.biz (i aliasu ${NR}.net.lab)" "10.21.${NR}.12")
    DNS_IP_LOCAL=$(hostname -I | awk '{print $1}')
    ZONES_DIR="/etc/bind/zones"
    SERIAL=$(date +%Y%m%d%H)

    BLOG_DOMAIN="${NR}.blog.pl"; BLOG_ALIAS="${NR}.edu.lab"
    BIZ_DOMAIN="${NR}.biz";     BIZ_ALIAS="${NR}.net.lab"

    echo "📦 Instaluję bind9…"
    apt update -y
    apt install -y bind9 bind9utils

    mkdir -p "$ZONES_DIR"

    make_zone() {
      local DOMAIN="$1" ALIAS="$2" TARGET="$3"
      cat >"${ZONES_DIR}/db.${DOMAIN}" <<EOF
$TTL 604800
@   IN SOA ns1.${DOMAIN}. admin.${DOMAIN}. (
   ${SERIAL}
   604800
   86400
   2419200
   604800 )
@     IN NS ns1.${DOMAIN}.
ns1   IN A  ${DNS_IP_LOCAL}
@     IN A  ${TARGET}
www   IN A  ${TARGET}
${ALIAS}.  IN CNAME ${DOMAIN}.
EOF
    }

    echo "📝 Tworzę strefy…"
    make_zone "$BLOG_DOMAIN" "$BLOG_ALIAS" "$BLOG_IP"
    make_zone "$BIZ_DOMAIN"  "$BIZ_ALIAS"  "$BIZ_IP"

    cat >/etc/bind/named.conf.local <<EOF
zone "${BLOG_DOMAIN}" { type master; file "${ZONES_DIR}/db.${BLOG_DOMAIN}"; };
zone "${BIZ_DOMAIN}"  { type master; file "${ZONES_DIR}/db.${BIZ_DOMAIN}";  };
EOF

    cat >/etc/bind/named.conf.options <<'EOF'
options {
  directory "/var/cache/bind";
  recursion yes;
  allow-query { any; };
  forwarders { 8.8.8.8; 8.8.4.4; };
  dnssec-validation auto;
};
EOF

    echo "✅ Walidacja…"
    named-checkconf
    named-checkzone "${BLOG_DOMAIN}" "${ZONES_DIR}/db.${BLOG_DOMAIN}"
    named-checkzone "${BIZ_DOMAIN}"  "${ZONES_DIR}/db.${BIZ_DOMAIN}"

    systemctl reload bind9 || systemctl restart bind9
    systemctl enable bind9 >/dev/null 2>&1 || true

    echo "🎉 DNS gotowy."
    echo "   ${BLOG_DOMAIN} (+ ${BLOG_ALIAS}) → ${BLOG_IP}"
    echo "   ${BIZ_DOMAIN}  (+ ${BIZ_ALIAS})  → ${BIZ_IP}"
    echo "👉 Na klientach ustaw:  nameserver ${DNS_IP_LOCAL}"
    ;;

  4)
    echo "=== [4] Podsumowanie / szybkie testy ==="
    echo "- Interfejsy:"
    ip -br addr
    echo
    echo "- Routing:"
    ip route
    echo
    echo "- ip_forward:"
    cat /proc/sys/net/ipv4/ip_forward
    echo
    echo "- iptables (nat):"
    iptables -t nat -S
    echo
    echo "🔎 Przykładowe testy:"
    echo "  ping 8.8.8.8"
    echo "  curl http://127.0.0.1:80  # jeśli reverse proxy/LB na VM04"
    echo "  dig ${NR:-137}.blog.pl @$(hostname -I | awk '{print $1}') +short"
    ;;

  0) echo "Bye!"; exit 0 ;;
  *) echo "❓ Nieznana opcja" ;;
  esac
done
